# Generated by Django 4.0.6 on 2022-07-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user_type",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
